const BUSINESS={name:'Shivay Tours & Travels',whatsapp:'919340568769',phone:'+919340568769'};
const categories=[
 {id:'sedan',title:'Sedan',desc:'Aura • Verna • City • Dzire',icon:'🚘'},
 {id:'seven',title:'7 Seater',desc:'Innova Crysta • Ertiga',icon:'🚐'}
];
const vehicles=[
 {id:'aura',category:'sedan',name:'Hyundai Aura',seats:4,bags:2,images:['https://commons.wikimedia.org/wiki/Special:Redirect/file/2020_Hyundai_Aura_Front.png','https://commons.wikimedia.org/wiki/Special:Redirect/file/2020_Hyundai_Aura_Rear.png']},
 {id:'verna',category:'sedan',name:'Hyundai Verna',seats:4,bags:2,images:['https://commons.wikimedia.org/wiki/Special:Redirect/file/2020_Hyundai_Verna_SX(O)_1.5_Diesel_front_view_(India).png','https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai_Verna_2019.jpg']},
 {id:'city',category:'sedan',name:'Honda City',seats:4,bags:2,images:['https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda_City_SV_2020.jpg','https://commons.wikimedia.org/wiki/Special:Redirect/file/Honda_City_2020.jpg']},
 {id:'dzire',category:'sedan',name:'Swift Dzire',seats:4,bags:2,images:['https://commons.wikimedia.org/wiki/Special:Redirect/file/Maruti_Suzuki_Dzire_VXi_VVT_(front).JPG','https://commons.wikimedia.org/wiki/Special:Redirect/file/Maruti_Suzuki_Dzire_VXi_VVT.JPG']},
 {id:'innova',category:'seven',name:'Innova Crysta',seats:7,bags:4,images:['https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Innova_Crysta_2.4_Z_front_right.jpg','https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Innova_Crysta_2.4_Z_side.jpg','https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Innova_Crysta_2.4_Z_rear_left.jpg']},
 {id:'ertiga',category:'seven',name:'Ertiga',seats:7,bags:3,images:['images/ertiga/ertiga_04_8k_web.jpg','images/ertiga/ertiga_03_8k_web.jpg','images/ertiga/ertiga_01_8k_web.jpg']}
];
let selectedVehicle=vehicles[0], activeCategory=null;
const cats=document.getElementById('fleetCategories'),panel=document.getElementById('fleetPanel'),grid=document.getElementById('vehicleGrid'),choice=document.getElementById('vehicleChoice');
const modal=document.getElementById('vehicleModal'),modalImage=document.getElementById('modalImage'),modalName=document.getElementById('modalName'),modalCategory=document.getElementById('modalCategory'),modalSeats=document.getElementById('modalSeats'),modalTags=document.getElementById('modalTags'),modalGallery=document.getElementById('modalGallery');
function imgFallback(img,v,index=0){img.onerror=()=>{img.onerror=null;if(v.id==='ertiga')img.src='images/ertiga/ertiga_01_8k_web.jpg';else{img.removeAttribute('src');img.alt=`${v.name} photo`;img.parentElement?.classList.add('image-missing')}}}
function renderCategories(){cats.innerHTML=categories.map(c=>`<button class="category-btn ${activeCategory===c.id?'active':''}" data-cat="${c.id}"><span class="cat-icon">${c.icon}</span><span><b>${c.title}</b><small>${c.desc}</small></span></button>`).join('');cats.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>openCategory(b.dataset.cat))}
function openCategory(id){activeCategory=id;renderCategories();const c=categories.find(x=>x.id===id);panel.hidden=false;document.getElementById('fleetPanelKicker').textContent='OUR FLEET • '+c.title.toUpperCase();document.getElementById('fleetPanelTitle').textContent=c.title;renderVehicles(id);panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
function renderVehicles(cat){const items=vehicles.filter(v=>v.category===cat);grid.innerHTML=items.map(v=>`<article class="vehicle-card"><div class="vehicle-photo"><img src="${v.images[0]}" alt="${v.name}" loading="lazy"><span class="badge">Premium Photo</span></div><div class="vehicle-body"><h3>${v.name}</h3><div class="vehicle-meta"><span>👤 ${v.seats} Seats</span><span>🧳 ${v.bags} Bags</span><span>❄ AC</span></div><div class="vehicle-actions"><button class="small-btn" data-view="${v.id}">View Photos</button><button class="small-btn primary" data-book="${v.id}">Book Now →</button></div></div></article>`).join('');grid.querySelectorAll('img').forEach((im,i)=>imgFallback(im,items[i]));grid.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openVehicle(b.dataset.view));grid.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>selectVehicle(b.dataset.book,true))}
function renderChoice(){choice.innerHTML=vehicles.map(v=>`<button type="button" class="vehicle-option ${v.id===selectedVehicle.id?'selected':''}" data-select="${v.id}"><img src="${v.images[0]}" alt="${v.name}"><span><b>${v.name}</b><small>${v.seats} seats • ${v.bags} bags • AC</small></span></button>`).join('');choice.querySelectorAll('img').forEach((im,i)=>imgFallback(im,vehicles[i]));choice.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>selectVehicle(b.dataset.select,false))}
function selectVehicle(id,scroll){selectedVehicle=vehicles.find(v=>v.id===id)||vehicles[0];renderChoice();if(scroll)document.getElementById('booking').scrollIntoView({behavior:'smooth'})}
function openVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v)return;selectedVehicle=v;renderChoice();modalName.textContent=v.name;modalCategory.textContent=categories.find(c=>c.id===v.category).title;modalSeats.textContent=`${v.seats} Seats`;modalTags.innerHTML=`<span>👤 ${v.seats} Seats</span><span>🧳 ${v.bags} Bags</span><span>❄ AC</span><span>✨ Premium Interior</span>`;modalImage.src=v.images[0];imgFallback(modalImage,v);modalGallery.innerHTML=v.images.map((src,i)=>`<button type="button"><img src="${src}" alt="${v.name} view ${i+1}"></button>`).join('');modalGallery.querySelectorAll('img').forEach(im=>imgFallback(im,v));modalGallery.querySelectorAll('button').forEach(b=>{const im=b.querySelector('img');b.onclick=()=>{modalImage.src=im.currentSrc||im.src}});modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.getElementById('modalClose').onclick=closeModal;modal.querySelector('.modal-backdrop').onclick=closeModal;document.getElementById('modalBook').onclick=()=>{closeModal();document.getElementById('booking').scrollIntoView({behavior:'smooth'});setTimeout(()=>document.getElementById('name').focus(),450)};document.getElementById('fleetPanelClose').onclick=()=>{panel.hidden=true;activeCategory=null;renderCategories()};
const nav=document.getElementById('nav');const menu=document.getElementById('menu');const heroMenu=document.getElementById('heroMenu');const navClose=document.getElementById('navClose');if(menu)menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));if(navClose)navClose.onclick=()=>nav.classList.remove('open');if(heroMenu)heroMenu.onclick=()=>nav.classList.toggle('open');
const date=document.getElementById('date');date.min=new Date().toISOString().slice(0,10);document.getElementById('year').textContent=new Date().getFullYear();
function wa(text){window.open(`https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
document.getElementById('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('.submit-btn'),result=document.getElementById('bookingResult');btn.disabled=true;btn.textContent='Saving booking…';const payload={name:document.getElementById('name').value.trim(),mobile:document.getElementById('mobile').value.trim(),pickup:document.getElementById('pickup').value.trim(),destination:document.getElementById('destination').value.trim(),travel_date:date.value,travel_time:document.getElementById('time').value,passengers:Number(document.getElementById('passengers').value),vehicle:selectedVehicle.name,vehicle_category:categories.find(c=>c.id===selectedVehicle.category).title,trip_type:document.getElementById('tripType').value,message:document.getElementById('message').value.trim()};try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Booking could not be saved.');const id=`SHV-${String(d.bookingId).padStart(5,'0')}`;result.style.display='block';result.textContent=`Booking ${id} saved successfully. Opening WhatsApp…`;wa(`🚕 *NEW SHIVAY BOOKING*\n\nBooking ID: *#${id}*\nName: ${payload.name}\nMobile: ${payload.mobile}\nPickup: ${payload.pickup}\nDrop: ${payload.destination}\nDate: ${payload.travel_date}\nTime: ${payload.travel_time}\nPassengers: ${payload.passengers}\nVehicle: ${payload.vehicle}\nCategory: ${payload.vehicle_category}\nTrip: ${payload.trip_type}\nNote: ${payload.message||'None'}\n\nPlease confirm availability & final fare.`);e.currentTarget.reset();renderChoice();date.min=new Date().toISOString().slice(0,10)}catch(err){result.style.display='block';result.textContent=err.message}finally{btn.disabled=false;btn.innerHTML='Confirm Booking & Open WhatsApp <span>→</span>'}});
renderCategories();renderChoice();
