const http = require('node:http'); const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto'); const { DatabaseSync } = require('node:sqlite');
const ROOT = __dirname, DATA = path.join(ROOT, 'data'); fs.mkdirSync(DATA, { recursive: true });
function loadEnv() { const p = path.join(ROOT, '.env'); if (!fs.existsSync(p)) return; for (const line of fs.readFileSync(p, 'utf8').split(/\r?\n/)) { const s = line.trim(); if (!s || s.startsWith('#')) continue; const i = s.indexOf('='); if (i < 0) continue; const k = s.slice(0, i).trim(), v = s.slice(i + 1).trim().replace(/^['"]|['"]$/g, ''); if (!process.env[k]) process.env[k] = v } } loadEnv();
const PORT = Number(process.env.PORT || 3000), ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'change-this-before-public-launch';
const db = new DatabaseSync(path.join(DATA, 'shivay.sqlite')); db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,created_at TEXT NOT NULL DEFAULT (datetime('now')),name TEXT NOT NULL,mobile TEXT NOT NULL,pickup TEXT NOT NULL,destination TEXT NOT NULL,travel_date TEXT NOT NULL,travel_time TEXT NOT NULL,passengers INTEGER NOT NULL,vehicle TEXT NOT NULL,vehicle_category TEXT NOT NULL,trip_type TEXT NOT NULL,message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'New');CREATE INDEX IF NOT EXISTS idx_date ON bookings(travel_date);CREATE INDEX IF NOT EXISTS idx_status ON bookings(status);`);
// Lightweight migration for older V12 databases.
const cols = db.prepare('PRAGMA table_info(bookings)').all().map(x => x.name); if (!cols.includes('travel_time')) db.exec("ALTER TABLE bookings ADD COLUMN travel_time TEXT NOT NULL DEFAULT '00:00'"); if (!cols.includes('vehicle_category')) db.exec("ALTER TABLE bookings ADD COLUMN vehicle_category TEXT NOT NULL DEFAULT 'Sedan'");
const sessions = new Map(); const statuses = ['New', 'Contacted', 'Confirmed', 'Completed', 'Cancelled']; const vehicleNames = ['Hyundai Aura', 'Hyundai Verna', 'Honda City', 'Swift Dzire', 'Innova Crysta', 'Ertiga'];
const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.ico': 'image/x-icon' };
function send(res, status, data, headers = {}) { const body = typeof data === 'string' ? data : JSON.stringify(data); res.writeHead(status, { 'Content-Type': typeof data === 'string' ? 'text/plain; charset=utf-8' : 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', ...headers }); res.end(body) }
function cookies(req) { return Object.fromEntries(String(req.headers.cookie || '').split(';').map(x => x.trim()).filter(Boolean).map(x => { const i = x.indexOf('='); return [x.slice(0, i), x.slice(i + 1)] })) } function authed(req) { const t = cookies(req).shivay_admin; return !!t && sessions.has(t) } function guard(req, res) { if (authed(req)) return true; send(res, 401, { error: 'Unauthorized' }); return false }
function clean(v, max = 500) { return String(v ?? '').trim().slice(0, max) } function mobile(v) { return /^[0-9+()\-\s]{7,20}$/.test(v) } function date(v) { return /^\d{4}-\d{2}-\d{2}$/.test(v) } function time(v) { return /^\d{2}:\d{2}$/.test(v) } async function json(req) { let raw = ''; for await (const c of req) { raw += c; if (raw.length > 32 * 1024) throw Error('Request too large') } return raw ? JSON.parse(raw) : {} }
function samePassword(a) { const x = Buffer.from(String(a)), y = Buffer.from(String(ADMIN_PASSWORD)); return x.length === y.length && crypto.timingSafeEqual(x, y) }
function booking(b) { return { name: clean(b.name, 80), mobile: clean(b.mobile, 30), pickup: clean(b.pickup, 160), destination: clean(b.destination, 160), travel_date: clean(b.travel_date, 10), travel_time: clean(b.travel_time, 5), passengers: Number(b.passengers), vehicle: clean(b.vehicle, 60), vehicle_category: clean(b.vehicle_category, 40), trip_type: clean(b.trip_type, 50), message: clean(b.message, 500) } }
async function api(req, res, url) {
    try {
        if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { ok: true, service: 'Shivay Tours & Travels' });
        if (req.method === 'POST' && url.pathname === '/api/bookings') { const b = booking(await json(req)); if (!b.name || !b.mobile || !b.pickup || !b.destination || !date(b.travel_date) || !time(b.travel_time) || !b.vehicle) return send(res, 400, { error: 'Please fill all required fields.' }); if (!mobile(b.mobile)) return send(res, 400, { error: 'Please enter a valid mobile number.' }); if (b.passengers < 1 || b.passengers > 7 || !Number.isInteger(b.passengers)) return send(res, 400, { error: 'Passengers must be between 1 and 7.' }); if (!vehicleNames.includes(b.vehicle)) return send(res, 400, { error: 'Invalid vehicle selected.' }); const r = db.prepare('INSERT INTO bookings(name,mobile,pickup,destination,travel_date,travel_time,passengers,vehicle,vehicle_category,trip_type,message) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(b.name, b.mobile, b.pickup, b.destination, b.travel_date, b.travel_time, b.passengers, b.vehicle, b.vehicle_category, b.trip_type, b.message); return send(res, 201, { ok: true, bookingId: Number(r.lastInsertRowid) }) }
        if (req.method === 'POST' && url.pathname === '/api/admin/login') { const b = await json(req); if (!samePassword(b.password)) return send(res, 401, { error: 'Incorrect password.' }); const t = crypto.randomBytes(32).toString('hex'); sessions.set(t, Date.now()); return send(res, 200, { ok: true }, { 'Set-Cookie': `shivay_admin=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800` }) }
        if (req.method === 'POST' && url.pathname === '/api/admin/logout') { if (!guard(req, res)) return; const t = cookies(req).shivay_admin; if (t) sessions.delete(t); return send(res, 200, { ok: true }, { 'Set-Cookie': 'shivay_admin=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0' }) }
        if (url.pathname === '/api/admin/stats' && req.method === 'GET') { if (!guard(req, res)) return; const counts = db.prepare("SELECT status,COUNT(*) count FROM bookings GROUP BY status").all(); const total = db.prepare('SELECT COUNT(*) count FROM bookings').get().count; const today = db.prepare("SELECT COUNT(*) count FROM bookings WHERE travel_date=date('now','localtime')").get().count; const vehicles = db.prepare('SELECT vehicle,COUNT(*) count FROM bookings GROUP BY vehicle ORDER BY count DESC').all(); return send(res, 200, { total, today, counts, vehicles }) }
        if (url.pathname === '/api/admin/bookings' && req.method === 'GET') { if (!guard(req, res)) return; const status = clean(url.searchParams.get('status'), 30); const q = clean(url.searchParams.get('q'), 80); let sql = 'SELECT * FROM bookings WHERE 1=1', args = []; if (status) { sql += ' AND status=?'; args.push(status) } if (q) { sql += ' AND (name LIKE ? OR mobile LIKE ? OR vehicle LIKE ? OR pickup LIKE ? OR destination LIKE ?)'; const s = '%' + q + '%'; args.push(s, s, s, s, s) } sql += ' ORDER BY id DESC'; return send(res, 200, { bookings: db.prepare(sql).all(...args) }) }
        const m = url.pathname.match(/^\/api\/admin\/bookings\/(\d+)$/); if (m) { if (!guard(req, res)) return; const id = Number(m[1]); if (req.method === 'PATCH') { const b = await json(req), status = clean(b.status, 30); if (!statuses.includes(status)) return send(res, 400, { error: 'Invalid status.' }); const r = db.prepare('UPDATE bookings SET status=? WHERE id=?').run(status, id); return r.changes ? send(res, 200, { ok: true }) : send(res, 404, { error: 'Booking not found.' }) } if (req.method === 'DELETE') { const r = db.prepare('DELETE FROM bookings WHERE id=?').run(id); return r.changes ? send(res, 200, { ok: true }) : send(res, 404, { error: 'Booking not found.' }) } }
        if (url.pathname === '/api/admin/export.csv' && req.method === 'GET') { if (!guard(req, res)) return; const rows = db.prepare('SELECT * FROM bookings ORDER BY id DESC').all(); const headers = ['id', 'created_at', 'name', 'mobile', 'pickup', 'destination', 'travel_date', 'travel_time', 'passengers', 'vehicle', 'vehicle_category', 'trip_type', 'message', 'status']; const esc = v => '"' + String(v ?? '').replaceAll('"', '""') + '"'; const csv = [headers.join(','), ...rows.map(r => headers.map(h => esc(r[h])).join(','))].join('\n'); return send(res, 200, csv, { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': 'attachment; filename="shivay-bookings.csv"' }) }
        return send(res, 404, { error: 'API route not found.' });
    } catch (e) { console.error(e); return send(res, 500, { error: 'Server error. Check terminal.' }) }
}
function serve(req, res, url) { let p = decodeURIComponent(url.pathname); if (p === '/') p = '/index.html'; if (p === '/admin') p = '/admin.html'; const file = path.normalize(path.join(ROOT, p)); if (!file.startsWith(ROOT)) return send(res, 403, 'Forbidden'); fs.stat(file, (e, s) => { if (e || !s.isFile()) return send(res, 404, 'Not found'); res.writeHead(200, { 'Content-Type': mime[path.extname(file).toLowerCase()] || 'application/octet-stream', 'X-Content-Type-Options': 'nosniff' }); fs.createReadStream(file).pipe(res) }) }
http.createServer(async (req, res) => { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (url.pathname.startsWith('/api/')) return api(req, res, url); if (req.method !== 'GET' && req.method !== 'HEAD') return send(res, 405, 'Method not allowed'); serve(req, res, url) }).listen(PORT, '0.0.0.0', () => { console.log(`Shivay Tours & Travels: http://localhost:${PORT}`); console.log(`Admin Panel: http://localhost:${PORT}/admin`); if (ADMIN_PASSWORD === 'change-this-before-public-launch') console.log('WARNING: set ADMIN_PASSWORD in .env before public launch.'); });
